### ISSUE TITLE
Uncaught TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by dbpolito** [xndcn/symbols-tree-view#28]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.2
**Thrown From**: [symbols-tree-view](https://github.com/xndcn/symbols-tree-view) package, v0.8.1

### Stack Trace

Uncaught TypeError: Cannot read property 'id' of undefined

```
At /Users/mac/.atom/packages/symbols-tree-view/node_modules/q/q.js:126

TypeError: Cannot read property 'id' of undefined
    at SymbolsTreeView.module.exports.SymbolsTreeView.updateContextMenu (/Users/mac/.atom/packages/symbols-tree-view/lib/symbols-tree-view.coffee:139:32)
    at /Users/mac/.atom/packages/symbols-tree-view/lib/symbols-tree-view.coffee:177:17
    at _fulfilled (/Users/mac/.atom/packages/symbols-tree-view/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/Users/mac/.atom/packages/symbols-tree-view/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/Users/mac/.atom/packages/symbols-tree-view/node_modules/q/q.js:749:13)
    at /Users/mac/.atom/packages/symbols-tree-view/node_modules/q/q.js:557:44
    at flush (/Users/mac/.atom/packages/symbols-tree-view/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:366:11)
```

### Commands

```
     -8:31.6 core:copy (atom-text-editor.editor)
     -8:31.3 fuzzy-finder:toggle-file-finder (atom-text-editor.editor)
     -8:31.1 core:paste (atom-text-editor.editor.mini)
 15x -8:30.2 core:move-left (atom-text-editor.editor.mini)
     -8:28.2 core:backspace (atom-text-editor.editor.mini)
  7x -8:27.8 core:move-left (atom-text-editor.editor.mini)
     -8:26.7 core:backspace (atom-text-editor.editor.mini)
     -8:25.8 editor:consolidate-selections (atom-text-editor.editor.mini)
     -8:25.8 core:cancel (atom-text-editor.editor.mini)
     -7:23.5 editor:toggle-line-comments (atom-text-editor.editor)
  3x -7:22.8 core:save (atom-text-editor.editor)
     -4:42.8 core:copy (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "one-dark-syntax"
    ],
    "disabledPackages": [
      "emmet"
    ]
  },
  "symbols-tree-view": {
    "autoHide": true,
    "autoToggle": true
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.23.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.6.0
autocomplete-snippets, v1.2.0
color-picker, v1.5.0
docblockr, v0.6.3
file-icons, v1.5.1
highlight-line, v0.10.1
highlight-selected, v0.9.1
language-blade, v0.12.0
minimap, v4.6.0
minimap-git-diff, v4.1.2
php-twig, v3.0.0
symbols-tree-view, v0.8.1

# Dev
No dev packages
```

**Comment by dbpolito** [comment]
This happened when i clicked to close all tabs.

**Comment by xndcn** [comment]
@dbpolito Please update and check it again, thanks!

**Comment by dbpolito** [comment]
Looks great, thanks!
