### ISSUE TITLE
Failed to load the symbols-tree-view package

### ISSUE THREAD

**Issue by flottin** [xndcn/symbols-tree-view#59]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.4
**System**: Ubuntu 14.04.2
**Thrown From**: [symbols-tree-view](https://github.com/xndcn/symbols-tree-view) package, v0.9.3

### Stack Trace

Failed to load the symbols-tree-view package

```
At Cannot find module 'atom-space-pen-views'

Error: Cannot find module 'atom-space-pen-views'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/home/flottin/.atom/packages/symbols-tree-view/lib/symbols-tree-view.coffee:8:11)
    at Object.<anonymous> (/home/flottin/.atom/packages/symbols-tree-view/lib/symbols-tree-view.coffee:347:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/usr/share/atom/resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "audioBeep": false
  }
}
```

### Installed Packages

```coffee
# User
minimap, v4.12.2
symbols-tree-view, v0.9.3

# Dev
No dev packages
```

**Comment by xndcn** [comment]
@flottin This is weird, I have reinstalled atom but I don't have this problem. Maybe you can try to access into the directory `/home/flottin/.atom/packages/symbols-tree-view/` then run this command `apm install`. 
You can also check whether there is a directory `atom-space-pen-views` under `/home/flottin/.atom/packages/symbols-tree-view/`

**Comment by jewirth** [comment]
Same issue here after downloading and extracting the package to ```.atom/packages/```. As xndcn proposed, doing ```apm install``` inside the package's directory solved the issue.

**Comment by jrial** [comment]
Same here; the apm install resolved it.

For those who stumble upon this, you can copy/paste the following command into your terminal:

```bash
cd $HOME/.atom/packages/symbols-tree-view/node_modules/ && apm install
```

After you done that, simply restart your Atom and the issue should be resolved.

@xndcn: feel free to copy/paste the generic solution above into your initial reply; people are more likely to see it there, and it saves them the trouble of editing flottin's username out of the commands you provided.
