### ISSUE TITLE
Cannot find module 'event-kit'

### ISSUE THREAD

**Issue by abduelhamit** [xndcn/symbols-tree-view#71]
1. Update Atom
2. Update symbols-tree-view

**Atom Version**: 1.0.19
**System**: MRYEAH-PC
**Thrown From**: [symbols-tree-view](https://github.com/xndcn/symbols-tree-view) package, v0.10.0

### Stack Trace

Failed to load the symbols-tree-view package

```
At Cannot find module 'event-kit'

Error: Cannot find module 'event-kit'
    at Module._resolveFilename (module.js:334:15)
    at Function.Module._resolveFilename (C:\Users\Abdülhamit\AppData\Local\atom\app-1.0.19\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (C:\Users\Abdülhamit\.atom\packages\symbols-tree-view\lib\tree-view.coffee:9:13)
    at Object.<anonymous> (C:\Users\Abdülhamit\.atom\packages\symbols-tree-view\lib\tree-view.coffee:304:4)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (C:\Users\Abdülhamit\AppData\Local\atom\app-1.0.19\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:353:32)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
altgr, v0.1.0
build, v0.47.0
file-icons, v1.6.9
go-plus, v3.5.1
keyboard-localization, v1.4.8
symbols-tree-view, v0.10.0

# Dev
No dev packages
```

**Comment by abduelhamit** [comment]
Fixed it. Atom tried to find the file in `C:\Users\Abdﾃｼlhamit` instead of `C:\Users\Abdülhamit`.

The fix was easy:

    C:\Users>mklink /J Abdﾃｼlhamit Abdülhamit
