### ISSUE TITLE
Uncaught TypeError: Cannot read property 'tags' of undefined

### ISSUE THREAD

**Issue by hedefalk** [xndcn/symbols-tree-view#79]
[Enter steps to reproduce below:]
Just happens once in a while.

**Atom Version**: 1.2.4
**System**: Mac OS X 10.11.1
**Thrown From**: [symbols-tree-view](https://github.com/xndcn/symbols-tree-view) package, v0.10.1

### Stack Trace

Uncaught TypeError: Cannot read property 'tags' of undefined

```
At /Users/viktor/.atom/packages/symbols-tree-view/lib/symbols-tree-view.coffee:83

TypeError: Cannot read property 'tags' of undefined
    at SymbolsTreeView.<anonymous> (/Users/viktor/.atom/packages/symbols-tree-view/lib/symbols-tree-view.coffee:83:17)
    at SymbolsTreeView.module.exports.SymbolsTreeView.focusClickedTag (/Users/viktor/.atom/packages/symbols-tree-view/lib/symbols-tree-view.coffee:83:17)
    at Object.callback (/Users/viktor/.atom/packages/symbols-tree-view/lib/main.coffee:57:11)
    at HyperclickForTextEditor._confirmSuggestion (/Users/viktor/.atom/packages/hyperclick/lib/HyperclickForTextEditor.js:72:20)
    at HyperclickForTextEditor._onMouseDown (/Users/viktor/.atom/packages/hyperclick/lib/HyperclickForTextEditor.js:127:14)
```

### Commands

```
     -0:51 snippets:expand (atom-text-editor.editor.is-focused)
     -0:50.9.0 editor:indent (atom-text-editor.editor.is-focused)
  2x -0:50.5.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:48 core:move-down (atom-text-editor.editor.is-focused)
 10x -0:47.4.0 core:select-down (atom-text-editor.editor.is-focused)
  2x -0:45.8.0 core:backspace (atom-text-editor.editor.is-focused)
  3x -0:43.6.0 core:undo (atom-text-editor.editor.is-focused)
     -0:42.1.0 core:move-up (atom-text-editor.editor.is-focused)
 11x -0:41.5.0 core:select-down (atom-text-editor.editor.is-focused)
     -0:40.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:39.5.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:39.3.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:35.7.0 core:save (atom-text-editor.editor.is-focused.hyperclick)
     -0:28.1.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:26.9.0 editor:delete-line (atom-text-editor.editor.is-focused)
     -0:26.3.0 core:save (atom-text-editor.editor.is-focused.hyperclick)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-dark-theme"
    ],
    "disabledPackages": [
      "linter-scalac"
    ],
    "ignoredNames": [
      ".git",
      ".ensime_cache",
      ".settings",
      ".idea",
      ".target",
      ".cache-main",
      ".cache-tests",
      "target"
    ]
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
Ensime, v0.31.1
Sublime-Style-Column-Selection, v1.3.0
atom-beautify, v0.28.19
auto-detect-indentation, v0.4.2
auto-indent, v0.5.0
emmet, v2.3.15
hyperclick, v0.0.35
indentation-indicator, v0.6.0
js-hyperclick, v1.4.1
language-scala, v1.1.4
language-vue, v0.8.0
language-vue-component, v0.3.0
last-cursor-position, v0.9.0
latex, v0.28.2
linter, v1.11.2
linter-jshint, v1.2.1
minimap, v4.16.2
pretty-json, v0.4.1
project-manager, v2.6.5
symbols-tree-view, v0.10.1

# Dev
No dev packages
```

**Comment by despairblue** [comment]
Happens every time when using nuclides hyperclick package.

**Comment by Tsury** [comment]
Any news on this one?

**Comment by cytsunny** [comment]
[Enter steps to reproduce:]

Happens right after login and start using the package.

**Atom**: 1.15.0 ia32
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Home N
**Thrown From**: [symbols-tree-view](https://github.com/xndcn/symbols-tree-view) package 0.13.2


### Stack Trace

Uncaught TypeError: Cannot read property 'tags' of undefined

```
At C:\Users\Sunny Chan\.atom\packages\symbols-tree-view\lib\symbols-tree-view.coffee:83

TypeError: Cannot read property 'tags' of undefined
    at /packages/symbols-tree-view/lib/symbols-tree-view.coffee:83:17)
    at SymbolsTreeView.module.exports.SymbolsTreeView.focusClickedTag (/packages/symbols-tree-view/lib/symbols-tree-view.coffee:83:17)
    at Object.callback (/packages/symbols-tree-view/lib/main.coffee:65:9)
    at HyperclickForTextEditor._confirmSuggestion (/packages/hyperclick/lib/HyperclickForTextEditor.js:124:20)
    at HyperclickForTextEditor._onMouseDown (/packages/hyperclick/lib/HyperclickForTextEditor.js:198:14)
```

### Commands

```
     -9:59.1.0 editor:consolidate-selections (input.hidden-input)
     -9:59.1.0 core:cancel (input.hidden-input)
     -9:58.5.0 pane:show-next-item (atom-workspace.workspace.scrollbars-visible-always.theme-one-light-syntax.theme-atom-light-ui.find-visible)
  2x -9:04.1.0 core:backspace (input.hidden-input)
     -9:03.0 intentions:highlight (input.hidden-input)
     -9:02.8.0 core:save (input.hidden-input)
     -9:00.8.0 editor:move-to-end-of-screen-line (input.hidden-input)
 23x -8:50 core:backspace (input.hidden-input)
     -8:48.1.0 intentions:highlight (input.hidden-input)
     -8:47.9.0 core:save (input.hidden-input)
     -1:33.6.0 intentions:highlight (input.hidden-input)
     -1:33.5.0 settings-view:open (input.hidden-input)
 90x -1:09.7.0 intentions:highlight (input.hidden-input)
```

### Non-Core Packages

```
angularjs 0.4.0 
atom-beautify 0.29.17 
auto-detect-indentation 1.3.0 
busy-signal 1.3.0 
diff-pane 0.1.0 
emmet 2.4.3 
file-type-icons 1.3.3 
file-watcher 1.0.2 
git-time-machine 1.5.4 
highlight-selected 0.12.0 
hyperclick 0.0.40 
increment-me 0.4.1 
indent-guide-improved 1.4.12 
intentions 1.1.2 
language-blade 0.27.1 
language-mjml 1.8.0 
language-todotxt 0.6.1 
less-autocompile 1.0.0 
linter 2.1.0 
linter-php 1.3.2 
linter-ui-default 1.2.1 
mjml-preview 1.2.0 
php-cs-fixer 4.1.0 
Remote-FTP 0.10.5 
split-diff 1.2.0 
Sublime-Style-Column-Selection 1.7.3 
symbols-tree-view 0.13.2 
sync-settings 0.8.1 
tabs-to-spaces 1.0.3 
```

**Comment by ntomka** [comment]
[Enter steps to reproduce:]

Happens when I click on a symbol to jump to it's origin using ctrl+click.

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: KDE neon
**Thrown From**: [symbols-tree-view](https://github.com/xndcn/symbols-tree-view) package 0.14.0


### Stack Trace

Uncaught TypeError: Cannot read property 'tags' of undefined

```
At /home/nagta/.atom/packages/symbols-tree-view/lib/symbols-tree-view.coffee:83

TypeError: Cannot read property 'tags' of undefined
    at /packages/symbols-tree-view/lib/symbols-tree-view.coffee:83:17)
    at SymbolsTreeView.module.exports.SymbolsTreeView.focusClickedTag (/packages/symbols-tree-view/lib/symbols-tree-view.coffee:83:17)
    at Object.callback (/packages/symbols-tree-view/lib/main.coffee:65:9)
    at HyperclickForTextEditor._confirmSuggestion (/packages/hyperclick/lib/HyperclickForTextEditor.js:124:20)
    at HyperclickForTextEditor._onMouseDown (/packages/hyperclick/lib/HyperclickForTextEditor.js:198:14)
```

### Commands

```
     -9:38.4.0 core:backspace (input.hidden-input)
     -9:37.6.0 intentions:highlight (input.hidden-input)
     -9:37.2.0 core:save (input.hidden-input)
     -9:34.4.0 core:move-right (input.hidden-input)
     -9:33 core:move-left (input.hidden-input)
     -9:32.7.0 core:move-right (input.hidden-input)
     -9:32 intentions:highlight (input.hidden-input)
     -9:31.8.0 core:save (input.hidden-input)
     -9:28.3.0 intentions:highlight (input.hidden-input)
     -9:28 git-control:toggle (input.hidden-input)
     -9:05.6.0 core:close (atom-workspace.workspace.scrollbars-visible-always.tinted-tab-bar.compact-tab-bar.use-animations.theme-atom-dark-syntax.theme-atom-material-ui.has-custom-icons)
     -1:12.6.0 intentions:highlight (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.23 
atom-material-syntax 1.0.2 
atom-material-ui 1.3.10 
busy-signal 1.4.1 
color-picker 2.2.5 
docblockr 0.9.4 
file-icons 2.1.4 
git-control 0.9.0 
highlight-selected 0.13.1 
hyperclick 0.0.40 
intentions 1.1.2 
language-twig 1.6.3 
linter 2.1.4 
linter-ui-default 1.2.4 
markdown-preview-plus 2.4.9 
minimap 4.28.2 
minimap-bookmarks 0.4.2 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-linter 2.0.0 
minimap-selection 4.4.0 
php-cs-fixer 4.1.0 
php-integrator-annotations 1.1.1 
php-integrator-autocomplete-plus 1.5.0 
php-integrator-base 2.1.11 
php-integrator-call-tips 1.2.1 
php-integrator-linter 1.3.0 
php-integrator-navigation 1.1.2 
php-integrator-refactoring 1.3.1 
php-integrator-symbol-viewer 0.6.4 
php-integrator-tooltips 1.1.5 
pigments 0.39.1 
project-manager 3.3.4 
symbols-tree-view 0.14.0 
todo-show 1.11.0 
```

**Comment by lgh06** [comment]
Same issue. hyperclick+atom-ternjs+symbols-tree-view

**Comment by griffin-stewie** [comment]
Same issue here.

**Comment by nicolashainaux** [comment]
@griffin-stewie @lgh06 For information, the bugfix from @russaa will be included in the next release of the forked package [symbols-tree-nav](https://atom.io/packages/symbols-tree-nav), hopefully in a few days.

**Comment by griffin-stewie** [comment]
@nicolashainaux  Thank you

**Comment by johnrizzo1** [comment]
I don't believe this has fixed the problem.  I just did a ctrl-click on a yaml file and I receive the same exception.

**Comment by nicolashainaux** [comment]
@johnrizzo1 Does it happen anytime you ctrl-click on this yaml file when you use [symbols-tree-nav](https://atom.io/packages/symbols-tree-nav)? If yes, then you're welcome to open a new issue [there](https://github.com/nicolashainaux/symbols-tree-nav/issues). If you use symbols-tree-view, afaik this patch has not been included nor published yet.

**Comment by AugustinGrigorov** [comment]
[Enter steps to reproduce:]

1. Every time I do command click on any item.

**Atom**: 1.19.7 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [symbols-tree-view](https://github.com/xndcn/symbols-tree-view) package 0.14.0


### Stack Trace

Uncaught TypeError: Cannot read property 'tags' of undefined

```
At /Users/augstingrigorov/.atom/packages/symbols-tree-view/lib/symbols-tree-view.coffee:83

TypeError: Cannot read property 'tags' of undefined
    at /packages/symbols-tree-view/lib/symbols-tree-view.coffee:83:17)
    at SymbolsTreeView.module.exports.SymbolsTreeView.focusClickedTag (/packages/symbols-tree-view/lib/symbols-tree-view.coffee:83:17)
    at Object.callback (/packages/symbols-tree-view/lib/main.coffee:65:9)
    at t.default._confirmSuggestion (/packages/hyperclick/index.js:1:158042)
    at t.default._onMouseDown (/packages/hyperclick/index.js:1:159072)
```

### Commands

```
     -1:54.5.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling)
```

### Non-Core Packages

```
apex-ui 1.0.1 
atom-beautify 0.30.5 
atom-material-syntax 1.0.6 
atom-material-ui 2.0.4 
atom-ternjs 0.18.3 
atomic-chrome 0.3.2 
autocomplete-paths 2.11.0 
busy-signal 1.4.3 
dash-syntax 0.3.0 
dash-ui 0.4.2 
file-icons 2.1.11 
hyperclick 0.1.5 
intentions 1.1.5 
linter 2.2.0 
linter-js-standard 4.0.1 
linter-ui-default 1.6.9 
merge-conflicts 1.4.5 
nord-atom-syntax 0.9.1 
pristine-ui 1.1.9 
symbols-tree-view 0.14.0 
```

**Comment by sinisarudan** [comment]
still unsolved ...
CTRL + Click:

1. works on some items
2. on some die silently
3. on some throws this error

![screen shot 2017-11-16 at 08 51 58](https://user-images.githubusercontent.com/1769627/32879740-78ee31bc-caab-11e7-89dc-beb8221bbd8d.png)

**Comment by eddydarell** [comment]
Exact same issue as @sinisarudan . Any possible fix? I am using Facebook's hyperlink as part of Atom IDE

**Comment by jonaswindey** [comment]
Same issue here.

For me I'm getting the problem when I click on a property instead of a direct link.

Let's say I have a function send() in `helper.js`

When I import it in an other file (`import helper from ./helper`) and I want to access the function send(), I get the error `Uncaught TypeError: Cannot read property 'tags' of undefined` (line 83 in symbols-tree-view.coffee). 

When I ctrl-click on `mailhelper` instead of `send` the link works.

**Comment by AndyCHK** [comment]
1 : Every time I do command click on any item to...

**Atom**: 1.21.0 x64
**Electron**: 1.6.9
**OS**: Ubuntu 16.04.4
**Thrown From**: [symbols-tree-view](https://github.com/xndcn/symbols-tree-view) package 0.14.0


### Stack Trace

Uncaught TypeError: Cannot read property 'tags' of undefined

```
At /home/andres/.atom/packages/symbols-tree-view/lib/symbols-tree-view.coffee:83

TypeError: Cannot read property 'tags' of undefined
    at /packages/symbols-tree-view/lib/symbols-tree-view.coffee:83:17)
    at SymbolsTreeView.module.exports.SymbolsTreeView.focusClickedTag (/packages/symbols-tree-view/lib/symbols-tree-view.coffee:83:17)
    at Object.callback (/packages/symbols-tree-view/lib/main.coffee:65:9)
    at HyperclickForTextEditor._confirmSuggestion (/packages/atom-ide-ui/modules/atom-ide-ui/pkg/hyperclick/lib/HyperclickForTextEditor.js:154:18)
    at HyperclickForTextEditor._onMouseDown (/packages/atom-ide-ui/modules/atom-ide-ui/pkg/hyperclick/lib/HyperclickForTextEditor.js:215:12)
```

### Commands

```
  7x -4:41 core:move-right (input.hidden-input)
     -4:02.4.0 intentions:highlight (input.hidden-input)
     -4:02.3.0 core:save (input.hidden-input)
     -3:01.0 editor:consolidate-selections (input.hidden-input)
     -3:01.0 core:cancel (input.hidden-input)
     -2:52.1.0 editor:newline (input.hidden-input)
     -2:48.2.0 core:move-down (input.hidden-input)
 17x -2:47.5.0 core:move-right (input.hidden-input)
     -2:29 tree-view:unfocus (div.tool-panel.tree-view)
     -2:28.4.0 editor:consolidate-selections (input.hidden-input)
     -2:28.4.0 core:cancel (input.hidden-input)
     -2:28.2.0 editor:consolidate-selections (input.hidden-input)
     -2:28.2.0 core:cancel (input.hidden-input)
     -0:24.7.0 intentions:highlight (input.hidden-input)
     -0:24.2.0 core:save (input.hidden-input)
     -0:22.7.0 intentions:highlight (input.hidden-input)
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
atom-beautify 0.32.2 
atom-ctags 5.1.2 
atom-ide-ui 0.9.4 
atom-symfony2 0.3.0 
auto-detect-indentation 1.3.0 
busy-signal 1.4.3 
ide-php 0.7.13 
intentions 1.1.5 
linter 2.2.0 
linter-php 1.5.1 
linter-ui-default 1.7.1 
php-cs-fixer 4.1.1 
php-debug 0.2.6 
php-integrator-base 3.2.1 
php-introspector 1.0.0 
php-twig 4.0.0 
project-manager 3.3.5 
symbols-tree-view 0.14.0 
```

**Comment by handicraftsman** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.26.0 x64
**Electron**: 1.8.4
**OS**: "Manjaro Linux"
**Thrown From**: [symbols-tree-view](https://github.com/xndcn/symbols-tree-view) package 0.14.0


### Stack Trace

Uncaught TypeError: Cannot read property 'tags' of undefined

```
At /home/ancient/.atom/packages/symbols-tree-view/lib/symbols-tree-view.coffee:83

TypeError: Cannot read property 'tags' of undefined
    at /packages/symbols-tree-view/lib/symbols-tree-view.coffee:83:17)
    at SymbolsTreeView.module.exports.SymbolsTreeView.focusClickedTag (/packages/symbols-tree-view/lib/symbols-tree-view.coffee:83:17)
    at Object.callback (/packages/symbols-tree-view/lib/main.coffee:65:9)
    at HyperclickForTextEditor._confirmSuggestion (/packages/atom-ide-ui/modules/atom-ide-ui/pkg/hyperclick/lib/HyperclickForTextEditor.js:149:18)
    at HyperclickForTextEditor._onMouseDown (/packages/atom-ide-ui/modules/atom-ide-ui/pkg/hyperclick/lib/HyperclickForTextEditor.js:212:12)
```

### Commands

```
  3x -2:04.7.0 editor:newline (input.hidden-input)
     -2:04.3.0 core:move-up (input.hidden-input)
     -2:04.0 snippets:next-tab-stop (input.hidden-input)
     -2:04.0 snippets:expand (input.hidden-input)
     -2:04.0 editor:indent (input.hidden-input)
     -2:01.5.0 editor:newline (input.hidden-input)
  3x -2:00.9.0 core:move-left (input.hidden-input)
  3x -2:00.2.0 core:move-right (input.hidden-input)
     -1:57.2.0 intentions:highlight (input.hidden-input)
     -1:57.2.0 core:save (input.hidden-input)
     -1:39.1.0 core:backspace (input.hidden-input)
     -1:39 intentions:highlight (input.hidden-input)
     -1:38.9.0 core:save (input.hidden-input)
     -1:12.4.0 editor:newline (input.hidden-input)
 13x -1:10.8.0 core:backspace (input.hidden-input)
     -0:34.7.0 intentions:highlight (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.11.1 
atom-toolbar 0.1.6 
autocomplete-clang 0.11.4 
busy-signal 1.4.3 
chester-atom-syntax 0.3.2 
dart 1.0.1 
file-icons 2.1.19 
ide-rust 0.16.0 
intentions 1.1.5 
language-cmake 1.1.0 
language-javascript-jsx 0.3.7 
language-pug 0.0.22 
language-rust 0.4.12 
language-webassembly 1.0.1 
linter 2.2.0 
linter-ui-default 1.7.1 
project-manager 3.3.5 
symbols-tree-view 0.14.0 
```

**Comment by DedMorozzz** [comment]
same issue

**Comment by pawel-grad** [comment]
Issue still occurs:

Steps to reproduce:
1. Ctrl + click on symbol

**Atom**: 1.32.2 x64
**Electron**: 2.0.9
**OS**: Ubuntu 18.04.1
**Thrown From**: [symbols-tree-view](https://github.com/xndcn/symbols-tree-view) package 0.14.0


### Stack Trace

Uncaught TypeError: Cannot read property 'tags' of undefined

```
At /home/pawel_grad/.atom/packages/symbols-tree-view/lib/symbols-tree-view.coffee:83

TypeError: Cannot read property 'tags' of undefined
    at /packages/symbols-tree-view/lib/symbols-tree-view.coffee:83:17)
    at SymbolsTreeView.module.exports.SymbolsTreeView.focusClickedTag (/packages/symbols-tree-view/lib/symbols-tree-view.coffee:83:17)
    at Object.callback (/packages/symbols-tree-view/lib/main.coffee:65:9)
    at HyperclickForTextEditor._confirmSuggestion (/packages/atom-ide-ui/modules/atom-ide-ui/pkg/hyperclick/lib/HyperclickForTextEditor.js:183:18)
    at HyperclickForTextEditor._onMouseDown (/packages/atom-ide-ui/modules/atom-ide-ui/pkg/hyperclick/lib/HyperclickForTextEditor.js:247:12)
```

### Commands

```
  2x -3:18 intentions:highlight (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-ide-ui 0.13.0 
atom-sync 0.7.3 
autocomplete-cmake 0.3.1 
autocomplete-ctags 0.4.1 
autocomplete-dcd 1.8.1 
autocomplete-python 1.11.0 
better-git-blame 0.4.7 
busy-signal 1.4.3 
copy-filename 1.1.0 
delete-lines 0.5.0 
docblockr 0.13.7 
dockerletion 0.2.0 
file-icons 2.1.26 
goto-definition 1.3.4 
highlight-selected 0.14.0 
ide-dlang 1.13.1 
ide-python 1.0.0 
intentions 1.1.5 
language-d 3.3.1 
language-docker 1.1.8 
language-r 0.4.2 
language-restructuredtext 1.1.2 
linter 2.2.0 
linter-docker 0.3.2 
linter-dscanner 0.2.5 
linter-flake8 2.3.0 
linter-ui-default 1.7.1 
markdown-scroll-sync 2.1.2 
minimap 4.29.9 
output-panel 0.3.4 
pandoc 0.2.2 
python-debugger 0.2.0 
python-indent 1.1.6 
python-isort 0.0.7 
python-tools 0.6.9 
rst-preview 1.3.1 
rst-preview-pandoc 0.1.12 
script 3.18.1 
split-diff 1.5.3 
Sublime-Style-Column-Selection 1.7.5 
symbols-tree-view 0.14.0 
tree-view-git-status 1.5.2 
```

**Comment by Tioborto** [comment]
+1
Any news ?

**Comment by DerZyklop** [comment]
When i start my Atom in the morning, this happens for a while on every cmd+click on a method in my TypeScript code. 

**After a minute or two it works fine.**
