### ISSUE TITLE
Failed to activate the symbols-tree-view package

### ISSUE THREAD

**Issue by MarkRobbins** [xndcn/symbols-tree-view#88]
[Enter steps to reproduce below:]

1. install
2. see error

**Atom Version**: 1.3.2
**System**: Microsoft Windows 7 Ultimate 
**Thrown From**: [symbols-tree-view](https://github.com/xndcn/symbols-tree-view) package, v0.11.0

### Stack Trace

Failed to activate the symbols-tree-view package

```
At Missing "providerName" property for hyperclick provider.

Error: Missing "providerName" property for hyperclick provider.
    at Object.consumeProvider (C:\Users\Administrator\.atom\packages\hyperclick\lib\main.js:32:13)
    at Provider.module.exports.Provider.provide (C:\Users\Administrator\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\service-hub\lib\provider.js:30:52)
    at ServiceHub.module.exports.ServiceHub.provide (C:\Users\Administrator\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\service-hub\lib\service-hub.js:30:20)
    at Package.module.exports.Package.activateServices (C:\Users\Administrator\AppData\Local\atom\app-1.3.2\resources\app.asar\src\package.js:330:71)
    at Package.module.exports.Package.activateNow (C:\Users\Administrator\AppData\Local\atom\app-1.3.2\resources\app.asar\src\package.js:173:16)
    at C:\Users\Administrator\AppData\Local\atom\app-1.3.2\resources\app.asar\src\package.js:150:32
    at Package.module.exports.Package.measure (C:\Users\Administrator\AppData\Local\atom\app-1.3.2\resources\app.asar\src\package.js:92:15)
    at C:\Users\Administrator\AppData\Local\atom\app-1.3.2\resources\app.asar\src\package.js:143:26
    at Package.module.exports.Package.activate (C:\Users\Administrator\AppData\Local\atom\app-1.3.2\resources\app.asar\src\package.js:140:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Administrator\AppData\Local\atom\app-1.3.2\resources\app.asar\src\package-manager.js:517:21)
    at C:\Users\Administrator\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\settings-view\lib\package-manager.js:444:29
    at exit (C:\Users\Administrator\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\settings-view\lib\package-manager.js:73:16)
    at triggerExitCallback (C:\Users\Administrator\AppData\Local\atom\app-1.3.2\resources\app.asar\src\buffered-process.js:213:47)
    at ChildProcess.<anonymous> (C:\Users\Administrator\AppData\Local\atom\app-1.3.2\resources\app.asar\src\buffered-process.js:235:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-js-standard",
      "bottom-dock",
      "linter-manager",
      "todo-manager",
      "minimap-autohide",
      "disable-keybindings",
      "video-player",
      "jumpy",
      "quick-jump",
      "highlight-selected",
      "multi-cursor-plus",
      "multi-cursor",
      "es6-javascript",
      "project-view",
      "project-colorize",
      "tool-bar-main",
      "activate-power-mode",
      "nuclide-fuzzy-filename-provider",
      "isearch",
      "symbol-gen",
      "atom-ctags",
      "language-jsx",
      "copy-",
      "open-plus",
      "tree-ignore"
    ],
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ],
    "packagesWithKeymapsDisabled": [
      "find-selection",
      "block-travel",
      "project-ring",
      "goto",
      "keyboard-scroll",
      "atom-focus-mode",
      "linter-eslint",
      "open-plus",
      "project-quick-open"
    ],
    "autoHideMenuBar": true,
    "followSymlinks": false
  }
}
```

### Installed Packages

```coffee
# User
advanced-open-file, v0.14.1
atom-commander, v0.5.1
atom-trello, v0.5.1
auto-fold, v0.2.0
autosave-plus, v0.5.2
block-cursor, v0.13.1
block-travel, v1.0.4
browser-plus, v0.0.54
build-tools-ant, v0.1.1
command-toolbar, v1.0.12
copy-path, v0.3.0
editor-background, v1.2.17
emmet, v2.3.17
es-identifier-highlight, v0.2.7
file-bookmark, v0.3.1
file-icons, v1.6.13
file-types, v0.5.1
flex-tool-bar, v0.7.3
fold-comments, v0.5.0
fold-functions, v0.4.3
grammar-token-limit, v0.1.1
highlight-column, v0.5.0
highlight-selected, v0.11.1
hyperclick, v0.0.35
imdone-atom, v1.3.16
js-hyperclick, v1.4.1
jshint, v1.8.3
keyboard-scroll, v0.4.0
keycodes, v0.1.4
language-babel, v2.6.3
language-javascript-jsx, v0.3.7
language-todo-extra-words, v0.2.0
line-count-status, v0.0.3
linter, v1.11.3
linter-eslint, v5.2.7
markdown-writer, v2.1.1
menu-manager, v0.4.3
meteor-api, v2.20.0
minimap, v4.19.0
minimap-bookmarks, v0.2.0
minimap-codeglance, v0.4.5
minimap-cursorline, v0.1.0
minimap-find-and-replace, v4.4.0
minimap-git-diff, v4.1.8
minimap-hide, v0.3.0
minimap-highlight-selected, v4.3.1
minimap-linter, v1.1.0
minimap-pigments, v0.1.7
minimap-selection, v4.3.1
navigate, v0.1.13
navigate-indent, v0.1.0
neon-selection, v0.3.2
nuclide-open-filenames-provider, v0.0.35
nuclide-quick-open, v0.0.35
nuclide-recent-files-provider, v0.0.35
nuclide-recent-files-service, v0.0.35
open-path, v0.3.3
open-this, v0.1.9
pigments, v0.19.5
preview-plus, v1.2.6
process-palette, v0.5.5
project-manager, v2.6.5
project-quick-open, v0.5.0
project-ring, v0.36.1
project-viewer, v0.2.26
quick-highlight, v0.3.9
react, v0.12.10
smartchr, v0.3.4
source-preview-react, v0.2.0
swackets, v0.9.3
swiq, v1.1.2
symbols-tree-view, v0.11.0
tasks, v2.6.0
terminal-plus, v0.14.5
tool-bar, v0.1.9
tool-bar-almighty, v0.5.0
tree-view-filter, v0.3.9
tree-view-git-branch, v0.0.6
tree-view-git-status, v0.2.2
tree-view-open-files, v0.3.0

# Dev
No dev packages
```

**Comment by joprice** [comment]
I just got this on a mac.
